---
apiVersion: v1
kind: Service
metadata:
  name: sparta-app-svc
  namespace: default
spec:
  ports:
  - nodePort: 30002 # NodePort service can use 30000-32768
    port: 3000
    targetPort: 3000
  selector:
    app: sparta-app  # Label to match service to deployment
  type: NodePort