---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  ports:
  - nodePort: 30001 # NodePort service can use 30000-32768
    port: 80
    targetPort: 80
  selector:
    app: nginx  # Label to match service to deployment
  type: NodePort