---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP # enables only internal access to ports and not externally like internet